let a = 'a'
let abbr = 'abbr'
let address = 'address'
let area = 'area'
let article = 'article'
let aside = 'aside'
let audio = 'audio'
let b = 'b'
let base = 'base'
let bdi = 'bdi'
let bdo = 'bdo'
let blockquote = 'blockquote'
let body = 'body'
let br = 'br'
let button = 'button'
let canvas = 'canvas'
let caption = 'caption'
let cite = 'cite'
let code = 'code'
let col = 'col'
let colgroup = 'colgroup'
let data = 'data'
let datalist = 'datalist'
let dd = 'dd'
let del = 'del'
let details = 'details'
let dfn = 'dfn'
let dialog = 'dialog'
let div = 'div'
let dl = 'dl'
let dt = 'dt'
let em = 'em'
let embed = 'embed'
let fieldset = 'fieldset'
let figcaption = 'figcaption'
let figure = 'figure'
let footer = 'footer'
let form = 'form'
let h1 = 'h1'
let h2 = 'h2'
let h3 = 'h3'
let h4 = 'h4'
let h5 = 'h5'
let h6 = 'h6'
let head = 'head'
let header = 'header'
let hgroup = 'hgroup'
let hr = 'hr'
let html = 'html'
let i = 'i'
let iframe = 'iframe'
let img = 'img'
let input = 'input'
let ins = 'ins'
let kbd = 'kbd'
let label = 'label'
let legend = 'legend'
let li = 'li'
let link = 'link'
let main = 'main'
let map = 'map'
let mark = 'mark'
let meta = 'meta'
let meter = 'meter'
let nav = 'nav'
let noscript = 'noscript'
let object = 'object'
let ol = 'ol'
let optgroup = 'optgroup'
let option = 'option'
let output = 'output'
let p = 'p'
let param = 'param'
let picture = 'picture'
let pre = 'pre'
let progress = 'progress'
let q = 'q'
let rp = 'rp'
let rt = 'rt'
let ruby = 'ruby'
let s = 's'
let samp = 'samp'
let script = 'script'
let section = 'section'
let slot = 'slot'
let small = 'small'
let source = 'source'
let span = 'span'
let strong = 'strong'
let style = 'style'
let sub = 'sub'
let summary = 'summary'
let sup = 'sup'
let table = 'table'
let tbody = 'tbody'
let td = 'td'
let template = 'template'
let textarea = 'textarea'
let tfoot = 'tfoot'
let th = 'th'
let thead = 'thead'
let time = 'time'
let title = 'title'
let tr = 'tr'
let track = 'track'
let u = 'u'
let ul = 'ul'
let varElement = 'var'
let video = 'video'
let wbr = 'wbr'


const select = (element) => document.querySelector(element)
const hide = (element) => select(element).style.display = 'none'
const unhide = (element, display='flex') => select(element).style.display = display
const blink = (element, duration = 500) => {
    setInterval(function() {
        hide(element)
        setTimeout(function() {
            unhide(element)
        }, duration)
    }, duration * 2)
}
const setText = (element, text) => select(element).textContent = text

const create = (type) => {
    document.createElement(type)
}

  